//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogZadatak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int BlogId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
